name: CI Pipeline

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t ihasangit/pipeline:${{ github.sha }} -t ihasan/pipeline:latest .
    - name: Push to Dockerhub
      run: |
        docker push ihasan72/pipeline:${{ github.sha }}
        docker push ihasan72/pipeline:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull Docker image
      run: sudo docker pull ihasan72/pipeline:latest

    - name: Deploy
      run: |
        # Add your deployment commands here